route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m

  receiver: discord

receivers:
  - name: discord
    discord_configs:
      - webhook_url: https://discord.com/api/webhooks/1224369555560992829/F4i0IODgolnhgdd0ka6I6hD8xMSJLVb4UlM1USsw49FitSR9x4yex1qf_27l0ZJYEQEd
